# Generated by Django 3.1.7 on 2021-03-18 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20210318_0351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='picture',
            new_name='content',
        ),
    ]
