# Generated by Django 3.1.7 on 2021-03-17 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20210317_0342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='texts',
            new_name='body',
        ),
    ]
